export const products = [
    {
        name: 'Shoe',
        price: 200,
        stock: 10,
        id: '1',
        img: 'https://www.trekkinn.com/f/13635/136356822/la-sportiva-pies-de-gato-tarantula.jpg',
        category: 'shoes',
    },
    {
        name: 'Shoe2',
        price: 222,
        stock: 10,
        id: '11',
        img: 'https://www.trekkinn.com/f/13635/136356822/la-sportiva-pies-de-gato-tarantula.jpg',
        category: 'shoes',
    },
    {
        name: 'Rope',
        price: 300,
        stock: 4,
        id: '2',
        img: 'https://www.trekkinn.com/f/13597/135970307/petzl-cuerda-club-10-mm.jpg',
        category: 'ropes',
    },
    {
        name: 'Rope2',
        price: 333,
        stock: 4,
        id: '22',
        img: 'https://www.trekkinn.com/f/13597/135970307/petzl-cuerda-club-10-mm.jpg',
        category: 'ropes',
    },
    {
        name: 'Express',
        price: 70,
        stock: 6,
        id: '3',
        img: 'https://www.trekkinn.com/f/13739/137394195/qiroc-conjunto-elektra-recto-clip-curvo-clip-expres-dyneema-12x120mm.jpg',
        category: 'expres',
    },
    {
        name: 'Express2',
        price: 77,
        stock: 6,
        id: '33',
        img: 'https://www.trekkinn.com/f/13739/137394195/qiroc-conjunto-elektra-recto-clip-curvo-clip-expres-dyneema-12x120mm.jpg',
        category: 'expres',
    },
    {
        name: 'Harness',
        price: 80,
        stock: 20,
        id: '4',
        img: 'https://www.trekkinn.com/f/13794/137944914/petzl-arnes-adjama.jpg',
        category: 'harness',
    },
    {
        name: 'Harness2',
        price: 88,
        stock: 20,
        id: '44',
        img: 'https://www.trekkinn.com/f/13794/137944914/petzl-arnes-adjama.jpg',
        category: 'harness',
    },
];
